#!/bin/bash
#
# Vanilla GRPO training on AWM environments using slime.
#
# Prerequisites:
#   1. Convert Qwen3-4B HF checkpoint to slime (Megatron) format
#   2. Run data_prep.py to generate training JSONL
#   3. AWM outputs (gen_envs.jsonl, databases/, gen_verifier.pure_code.jsonl) must exist
#
# Hardware: 2x H100 (colocated training + rollout)
#

# ── Cleanup ──────────────────────────────────────────────────────────────────
pkill -9 sglang 2>/dev/null
sleep 2
ray stop --force 2>/dev/null
pkill -9 ray 2>/dev/null
sleep 2

set -ex

export PYTHONUNBUFFERED=1

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SLIME_DIR="${SCRIPT_DIR}/../slime"
AWM_DIR="${SCRIPT_DIR}/../agent-world-model"
MEGATRON_DIR="${SLIME_DIR}/../Megatron-LM"  # adjust as needed

# Model checkpoints (adjust these paths)
HF_CKPT="${HF_CKPT:-/path/to/Qwen3-4B}"
SLIME_CKPT="${SLIME_CKPT:-/path/to/Qwen3-4B_slime}"
REF_CKPT="${REF_CKPT:-/path/to/Qwen3-4B_torch_dist}"
SAVE_DIR="${SAVE_DIR:-${SCRIPT_DIR}/checkpoints/awm_grpo}"

# Training data (generated by data_prep.py)
TRAIN_DATA="${SCRIPT_DIR}/data/train.jsonl"
VAL_DATA="${SCRIPT_DIR}/data/val.jsonl"

# ── Model architecture (Qwen3-4B) ───────────────────────────────────────────
MODEL_ARGS=(
   --swiglu
   --num-layers 36
   --hidden-size 2560
   --ffn-hidden-size 9728
   --num-attention-heads 32
   --group-query-attention
   --num-query-groups 8
   --use-rotary-position-embeddings
   --disable-bias-linear
   --normalization "RMSNorm"
   --norm-epsilon 1e-6
   --rotary-base 5000000
   --vocab-size 151936
   --kv-channels 128
   --qk-layernorm
)

# ── Checkpoint args ──────────────────────────────────────────────────────────
CKPT_ARGS=(
   --hf-checkpoint "${HF_CKPT}"
   --ref-load "${REF_CKPT}"
   --load "${SLIME_CKPT}"
   --save "${SAVE_DIR}"
   --save-interval 10
)

# ── Rollout args ─────────────────────────────────────────────────────────────
ROLLOUT_ARGS=(
   --prompt-data "${TRAIN_DATA}"
   --input-key text
   --metadata-key metadata
   --apply-chat-template
   --rollout-shuffle
   --num-rollout 200
   --rollout-batch-size 16
   --n-samples-per-prompt 4
   # AWM tool-heavy prompts can be long; allow generous response
   --rollout-max-response-len 4096
   --rollout-temperature 1.0
   --global-batch-size 64
   --balance-data
   --dynamic-sampling-filter-path slime.rollout.filter_hub.dynamic_sampling_filters.check_reward_nonzero_std
)

# ── Eval args ────────────────────────────────────────────────────────────────
EVAL_ARGS=(
   --eval-interval 10
   --eval-prompt-data awm-val "${VAL_DATA}"
   --n-samples-per-eval-prompt 1
   --eval-max-response-len 4096
   --eval-top-k 1
)

# ── Performance args (2x H100, TP=2) ────────────────────────────────────────
PERF_ARGS=(
   --tensor-model-parallel-size 2
   --sequence-parallel
   --pipeline-model-parallel-size 1
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1
   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1
   --use-dynamic-batch-size
   --max-tokens-per-gpu 8192
)

# ── GRPO args (vanilla outcome-only) ────────────────────────────────────────
GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef 0.001
   --kl-loss-type low_var_kl
   --entropy-coef 0.0
   --eps-clip 0.2
   --eps-clip-high 0.28
)

# ── Optimizer args ───────────────────────────────────────────────────────────
OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 1e-6
   --lr-decay-style constant
   --weight-decay 0.1
   --adam-beta1 0.9
   --adam-beta2 0.98
)

# ── SGLang args ──────────────────────────────────────────────────────────────
SGLANG_ARGS=(
   --rollout-num-gpus-per-engine 1
   --sglang-mem-fraction-static 0.65
)

# ── Misc args ────────────────────────────────────────────────────────────────
MISC_ARGS=(
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
)

# ── Custom args (AWM rollout + reward) ───────────────────────────────────────
CUSTOM_ARGS=(
   --custom-generate-function-path rollout.generate
   --custom-rm-path reward.async_rm
   --custom-config-path "${SCRIPT_DIR}/awm_config.yaml"
)

# ── Weights & Biases (optional) ─────────────────────────────────────────────
WANDB_ARGS=(
   # --use-wandb
   # --wandb-project awm-grpo
   # --wandb-group qwen3-4B-vanilla
   # --wandb-key ${WANDB_KEY}
)

# ── Launch Ray ───────────────────────────────────────────────────────────────
export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
NUM_GPUS=2

ray start --head \
    --node-ip-address "${MASTER_ADDR}" \
    --num-gpus ${NUM_GPUS} \
    --disable-usage-stats \
    --dashboard-host=0.0.0.0 \
    --dashboard-port=8265

# ── Build runtime env ────────────────────────────────────────────────────────
RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"${MEGATRON_DIR}:${SCRIPT_DIR}:${SLIME_DIR}:${AWM_DIR}\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\"
  }
}"

# ── Submit training job ──────────────────────────────────────────────────────
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 "${SLIME_DIR}/train.py" \
   --actor-num-nodes 1 \
   --actor-num-gpus-per-node ${NUM_GPUS} \
   --rollout-num-gpus ${NUM_GPUS} \
   --colocate \
   "${MODEL_ARGS[@]}" \
   "${CKPT_ARGS[@]}" \
   "${ROLLOUT_ARGS[@]}" \
   "${OPTIMIZER_ARGS[@]}" \
   "${GRPO_ARGS[@]}" \
   "${PERF_ARGS[@]}" \
   "${EVAL_ARGS[@]}" \
   "${SGLANG_ARGS[@]}" \
   "${MISC_ARGS[@]}" \
   "${CUSTOM_ARGS[@]}" \
   "${WANDB_ARGS[@]}"
