#!/bin/bash
#
# Vanilla GRPO training on AWM environments using slime.
#
# Prerequisites:
#   1. Convert Qwen3-4B HF checkpoint to slime (Megatron) format
#   2. Run data_prep.py to generate training JSONL
#   3. AWM outputs (gen_envs.jsonl, databases/, gen_verifier.pure_code.jsonl) must exist
#
# Hardware: single node, colocated training + rollout
#
# Quick start (after running setup.sh):
#   source .env && bash run_awm_grpo.sh              # Full training
#   source .env && NUM_ROLLOUT=3 bash run_awm_grpo.sh  # Smoke test
#

# ── Load .env if present (generated by setup.sh) ──────────────────────────
SCRIPT_DIR_EARLY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
if [ -f "${SCRIPT_DIR_EARLY}/.env" ]; then
    source "${SCRIPT_DIR_EARLY}/.env"
fi

# ── Cleanup ──────────────────────────────────────────────────────────────────
pkill -9 sglang 2>/dev/null
sleep 2
ray stop --force 2>/dev/null
pkill -9 ray 2>/dev/null
sleep 2

set -ex

export PYTHONUNBUFFERED=1
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"

NVLINK_COUNT=$(nvidia-smi topo -m 2>/dev/null | grep -o 'NV[0-9][0-9]*' | wc -l)
if [ "${NVLINK_COUNT}" -gt 0 ]; then
    HAS_NVLINK=1
else
    HAS_NVLINK=0
fi

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SLIME_DIR="${SCRIPT_DIR}/../slime"
AWM_DIR="${SCRIPT_DIR}/../agent-world-model"
MEGATRON_DIR="${SLIME_DIR}/../Megatron-LM"  # adjust as needed

# Model checkpoints (adjust these paths)
HF_CKPT="${HF_CKPT:-/workspace/models/Qwen3-4B}"
REF_CKPT="${REF_CKPT:-/workspace/models/Qwen3-4B_torch_dist}"
SAVE_DIR="${SAVE_DIR:-${SCRIPT_DIR}/checkpoints/awm_grpo}"
# Fresh runs should let --load point at SAVE_DIR so slime initializes from
# REF_CKPT and starts from rollout 0. RESUME_CKPT is only for resuming an
# existing training directory with optimizer / rollout state.
RESUME_CKPT="${RESUME_CKPT:-${SLIME_CKPT:-${SAVE_DIR}}}"
if [ "${RESUME_CKPT}" = "${REF_CKPT}" ]; then
    echo "RESUME_CKPT matches REF_CKPT; treating this as a fresh run from SAVE_DIR."
    RESUME_CKPT="${SAVE_DIR}"
fi

# Launch / throughput knobs
NUM_GPUS="${NUM_GPUS:-4}"
NUM_ROLLOUT="${NUM_ROLLOUT:-200}"
# For multi-turn rollouts each sample runs many SGLang calls + env steps,
# so keep batch sizes modest to avoid overwhelming the RolloutManager.
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-8}"
OVER_SAMPLING_BATCH_SIZE="${OVER_SAMPLING_BATCH_SIZE:-16}"
N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-4}"
# Qwen3-4B uses <think> blocks that can consume 2-4k tokens before any tool
# call.  With 15 max turns, each turn producing ~1-2k tokens, we need a
# generous budget.  16384 allows ~4k think + ~12k for tool-call rounds.
ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-16384}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-32}"
# Match the longer sequences
MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-16384}"
ROLLOUT_NUM_GPUS="${ROLLOUT_NUM_GPUS:-${NUM_GPUS}}"
ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.55}"
ROUTER_POLICY="${ROUTER_POLICY:-round_robin}"
# Multi-turn: each concurrent sample holds a semaphore slot for the full
# episode (multiple SGLang calls).  Set high enough that SGLang engines can
# batch multiple requests.  The AWM semaphore (= server_pool_max_servers)
# is the real concurrency gate.
SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY:-8}"
SAVE_INTERVAL="${SAVE_INTERVAL:-10}"
EVAL_INTERVAL="${EVAL_INTERVAL:-10}"
SKIP_EVAL_BEFORE_TRAIN="${SKIP_EVAL_BEFORE_TRAIN:-1}"
DYNAMIC_SAMPLING_FILTER_PATH="${DYNAMIC_SAMPLING_FILTER_PATH-slime.rollout.filter_hub.dynamic_sampling_filters.check_reward_nonzero_std}"
PREWARM_TEMPLATES="${PREWARM_TEMPLATES:-1}"

# Training data (generated by data_prep.py)
TRAIN_DATA="${SCRIPT_DIR}/data/train.jsonl"
VAL_DATA="${SCRIPT_DIR}/data/val.jsonl"

# ── Model architecture (Qwen3-4B) ───────────────────────────────────────────
MODEL_ARGS=(
   --swiglu
   --num-layers 36
   --hidden-size 2560
   --ffn-hidden-size 9728
   --num-attention-heads 32
   --group-query-attention
   --num-query-groups 8
   --use-rotary-position-embeddings
   --disable-bias-linear
   --normalization "RMSNorm"
   --norm-epsilon 1e-6
   --rotary-base 1000000
   --vocab-size 151936
   --kv-channels 128
   --qk-layernorm
)

# ── Checkpoint args ──────────────────────────────────────────────────────────
CKPT_ARGS=(
   --hf-checkpoint "${HF_CKPT}"
   --ref-load "${REF_CKPT}"
   --load "${RESUME_CKPT}"
   --save "${SAVE_DIR}"
   --save-interval "${SAVE_INTERVAL}"
)

# ── Rollout args ─────────────────────────────────────────────────────────────
ROLLOUT_ARGS=(
   --prompt-data "${TRAIN_DATA}"
   --input-key text
   --metadata-key metadata
   --apply-chat-template
   --rollout-shuffle
   --num-rollout "${NUM_ROLLOUT}"
   --rollout-batch-size "${ROLLOUT_BATCH_SIZE}"
   --over-sampling-batch-size "${OVER_SAMPLING_BATCH_SIZE}"
   --n-samples-per-prompt "${N_SAMPLES_PER_PROMPT}"
   # AWM tool-heavy prompts can be long; allow generous response
   --rollout-max-response-len "${ROLLOUT_MAX_RESPONSE_LEN}"
   --rollout-temperature 1.0
   --global-batch-size "${GLOBAL_BATCH_SIZE}"
   --balance-data
)
if [ -n "${DYNAMIC_SAMPLING_FILTER_PATH}" ]; then
   ROLLOUT_ARGS+=(--dynamic-sampling-filter-path "${DYNAMIC_SAMPLING_FILTER_PATH}")
fi

# ── Eval args ────────────────────────────────────────────────────────────────
EVAL_ARGS=()
if [ "${EVAL_INTERVAL}" -gt 0 ]; then
   EVAL_ARGS+=(--eval-interval "${EVAL_INTERVAL}")
fi
if [ "${SKIP_EVAL_BEFORE_TRAIN}" = "1" ]; then
   EVAL_ARGS+=(--skip-eval-before-train)
fi
EVAL_ARGS+=(
   --eval-prompt-data awm-val "${VAL_DATA}"
   --n-samples-per-eval-prompt 1
   --eval-max-response-len 4096
   --eval-top-k 1
)

# ── Performance args ─────────────────────────────────────────────────────────
# TP=2 with 4 GPUs → 2 DP ranks for training, 4 SGLang engines (1 GPU each).
# For a 4B model on H200, TP=1 would work and give more DP parallelism, but
# requires re-converting the checkpoint.  Use TP=1 if checkpoint supports it.
TP_SIZE="${TP_SIZE:-1}"
PERF_ARGS=(
   --tensor-model-parallel-size "${TP_SIZE}"
   --pipeline-model-parallel-size 1
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1
   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1
   --use-dynamic-batch-size
   --max-tokens-per-gpu "${MAX_TOKENS_PER_GPU}"
)
if [ "${TP_SIZE}" -gt 1 ]; then
   PERF_ARGS+=(--sequence-parallel)
fi

# ── GRPO args (vanilla outcome-only) ────────────────────────────────────────
GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef 0.001
   --kl-loss-type low_var_kl
   --entropy-coef 0.0
   --eps-clip 0.2
   --eps-clip-high 0.28
)

# ── Optimizer args ───────────────────────────────────────────────────────────
OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 1e-6
   --lr-decay-style constant
   --weight-decay 0.1
   --adam-beta1 0.9
   --adam-beta2 0.98
)

# ── SGLang args ──────────────────────────────────────────────────────────────
SGLANG_ARGS=(
   --rollout-num-gpus-per-engine "${ROLLOUT_NUM_GPUS_PER_ENGINE}"
   --sglang-mem-fraction-static "${SGLANG_MEM_FRACTION_STATIC}"
   --sglang-server-concurrency "${SGLANG_SERVER_CONCURRENCY}"
)

ROUTER_ARGS=(
   --router-policy "${ROUTER_POLICY}"
)

# ── Misc args ────────────────────────────────────────────────────────────────
MISC_ARGS=(
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --no-gradient-accumulation-fusion
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
)

# ── Custom args (AWM rollout + reward) ───────────────────────────────────────
CUSTOM_ARGS=(
   --custom-generate-function-path rollout.generate
   --custom-rm-path reward.async_rm
   --custom-rollout-log-function-path rollout_logging.log_rollout_data
   --custom-config-path "${SCRIPT_DIR}/awm_config.yaml"
)

# ── Weights & Biases (optional) ─────────────────────────────────────────────
WANDB_ARGS=(
   # --use-wandb
   # --wandb-project awm-grpo
   # --wandb-group qwen3-4B-vanilla
   # --wandb-key ${WANDB_KEY}
)

# ── Launch Ray ───────────────────────────────────────────────────────────────
export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}

if [ "${PREWARM_TEMPLATES}" = "1" ]; then
   echo "Prewarming template databases..."
   PYTHONPATH="${AWM_DIR}:${SCRIPT_DIR}:${PYTHONPATH:-}" python "${SCRIPT_DIR}/prewarm_templates.py" \
      --prompt-data "${TRAIN_DATA}" "${VAL_DATA}" \
      --db-schema-path "${AWM_DIR}/outputs/gen_db.jsonl" \
      --sample-path "${AWM_DIR}/outputs/gen_sample.jsonl" \
      --verifier-path "${AWM_DIR}/outputs/gen_verifier.pure_code.jsonl" \
      --envs-path "${AWM_DIR}/outputs/gen_envs.jsonl" \
      --db-dir "${AWM_DIR}/outputs/databases"
   echo "Prewarm done."
fi

ray start --head \
    --node-ip-address "${MASTER_ADDR}" \
    --num-gpus ${NUM_GPUS} \
    --disable-usage-stats \
    --dashboard-host=0.0.0.0 \
    --dashboard-port=8265

# Wait for Ray dashboard to be ready before submitting jobs
echo "Waiting for Ray dashboard..."
for i in $(seq 1 30); do
    if curl -s http://127.0.0.1:8265/api/version >/dev/null 2>&1; then
        echo "Ray dashboard ready."
        break
    fi
    sleep 1
done

# ── Build runtime env ────────────────────────────────────────────────────────
RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"${MEGATRON_DIR}:${SCRIPT_DIR}:${SLIME_DIR}:${AWM_DIR}\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\",
    \"NCCL_NVLS_ENABLE\": \"${HAS_NVLINK}\",
    \"MASTER_ADDR\": \"${MASTER_ADDR}\",
    \"no_proxy\": \"127.0.0.1,${MASTER_ADDR}\",
    \"OPENBLAS_NUM_THREADS\": \"${OPENBLAS_NUM_THREADS}\",
    \"OMP_NUM_THREADS\": \"${OMP_NUM_THREADS}\",
    \"MKL_NUM_THREADS\": \"${MKL_NUM_THREADS}\",
    \"NUMEXPR_NUM_THREADS\": \"${NUMEXPR_NUM_THREADS}\",
    \"RAYON_NUM_THREADS\": \"${RAYON_NUM_THREADS}\",
    \"TOKENIZERS_PARALLELISM\": \"${TOKENIZERS_PARALLELISM}\"
  }
}"

# ── Submit training job ──────────────────────────────────────────────────────
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 "${SLIME_DIR}/train.py" \
   --actor-num-nodes 1 \
   --actor-num-gpus-per-node ${NUM_GPUS} \
   --rollout-num-gpus ${ROLLOUT_NUM_GPUS} \
   --num-gpus-per-node ${NUM_GPUS} \
   --colocate \
   "${MODEL_ARGS[@]}" \
   "${CKPT_ARGS[@]}" \
   "${ROLLOUT_ARGS[@]}" \
   "${OPTIMIZER_ARGS[@]}" \
   "${GRPO_ARGS[@]}" \
   "${PERF_ARGS[@]}" \
   "${EVAL_ARGS[@]}" \
   "${SGLANG_ARGS[@]}" \
   "${ROUTER_ARGS[@]}" \
   "${MISC_ARGS[@]}" \
   "${CUSTOM_ARGS[@]}" \
   "${WANDB_ARGS[@]}"
