#!/bin/bash
#
# AWM-GRPO training launcher.
# Reads configuration from config.yaml (user-editable).
#
# Usage:
#   bash run_awm_grpo.sh                    # Use default config.yaml
#   bash run_awm_grpo.sh --config my.yaml   # Use custom config
#   NUM_ROLLOUT=3 bash run_awm_grpo.sh      # Env vars still override everything
#

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# ── Parse CLI args ────────────────────────────────────────────────────────
CONFIG_FILE="${SCRIPT_DIR}/config.yaml"
while [[ $# -gt 0 ]]; do
    case $1 in
        --config) CONFIG_FILE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── Load config.yaml → shell variables (env vars take precedence) ─────────
if [ -f "${CONFIG_FILE}" ]; then
    echo "Loading config from ${CONFIG_FILE}"
    # parse_config.py exports variables; we eval them but existing env vars win
    _PARSED=$(python3 "${SCRIPT_DIR}/parse_config.py" "${CONFIG_FILE}" 2>/dev/null)
    while IFS= read -r line; do
        # Extract var name: 'export FOO="bar"' → FOO
        var_name=$(echo "$line" | sed -n 's/^export \([A-Z_]*\)=.*/\1/p')
        if [ -n "$var_name" ]; then
            # Only set if not already in environment (env vars override yaml)
            if [ -z "${!var_name+x}" ]; then
                eval "$line"
            fi
        fi
    done <<< "${_PARSED}"
else
    echo "Warning: ${CONFIG_FILE} not found, using defaults."
fi

# ── Load .env if present (generated by setup.sh) ─────────────────────────
if [ -f "${SCRIPT_DIR}/.env" ]; then
    source "${SCRIPT_DIR}/.env"
fi

# ── Cleanup stale processes ───────────────────────────────────────────────
pkill -9 sglang 2>/dev/null
sleep 2
ray stop --force 2>/dev/null
pkill -9 ray 2>/dev/null
sleep 2

set -ex

export PYTHONUNBUFFERED=1
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"

NVLINK_COUNT=$(nvidia-smi topo -m 2>/dev/null | grep -o 'NV[0-9][0-9]*' | wc -l)
HAS_NVLINK=$( [ "${NVLINK_COUNT}" -gt 0 ] && echo 1 || echo 0 )

# ── Paths ─────────────────────────────────────────────────────────────────
SLIME_DIR="${SCRIPT_DIR}/../slime"
AWM_DIR="${SCRIPT_DIR}/../agent-world-model"
MEGATRON_DIR="${SLIME_DIR}/../Megatron-LM"

HF_CKPT="${HF_CKPT:-/workspace/models/Qwen3-4B}"
REF_CKPT="${REF_CKPT:-/workspace/models/Qwen3-4B_torch_dist}"
SAVE_DIR="${SAVE_DIR:-${SCRIPT_DIR}/checkpoints/awm_grpo}"
RESUME_CKPT="${RESUME_CKPT:-${SAVE_DIR}}"
if [ "${RESUME_CKPT}" = "${REF_CKPT}" ]; then
    echo "RESUME_CKPT matches REF_CKPT; treating as fresh run."
    RESUME_CKPT="${SAVE_DIR}"
fi

# ── Auto-detect GPU and set profile defaults ──────────────────────────────
if [ "${NUM_GPUS:-auto}" = "auto" ]; then
    NUM_GPUS=$(nvidia-smi -L 2>/dev/null | wc -l)
fi
GPU_MEM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
GPU_MEM_GB=$((GPU_MEM_MB / 1024))

if [ "${GPU_MEM_GB}" -ge 120 ]; then
    GPU_PROFILE="large"; D_RESP=16384; D_TOK=16384; D_MEM=0.55; D_BATCH=8; D_POOL=16; D_CONC=8
elif [ "${GPU_MEM_GB}" -ge 70 ]; then
    GPU_PROFILE="medium"; D_RESP=8192; D_TOK=8192; D_MEM=0.45; D_BATCH=4; D_POOL=8; D_CONC=4
else
    GPU_PROFILE="small"; D_RESP=4096; D_TOK=4096; D_MEM=0.35; D_BATCH=2; D_POOL=4; D_CONC=2
fi
echo "GPU: ${NUM_GPUS}× $(nvidia-smi --query-gpu=name --format=csv,noheader | head -1) (${GPU_MEM_GB} GB, profile=${GPU_PROFILE})"

# ── Fill in any remaining "auto" / unset values from profile ──────────────
NUM_ROLLOUT="${NUM_ROLLOUT:-200}"
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-${D_BATCH}}"
N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-4}"
OVER_SAMPLING_BATCH_SIZE="${OVER_SAMPLING_BATCH_SIZE:-$((ROLLOUT_BATCH_SIZE * 2))}"
ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-${D_RESP}}"
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))}"
MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-${D_TOK}}"
ROLLOUT_NUM_GPUS="${ROLLOUT_NUM_GPUS:-${NUM_GPUS}}"
TRAIN_NUM_GPUS="${TRAIN_NUM_GPUS:-${NUM_GPUS}}"
# Colocate mode: set COLOCATE=0 to use separate GPUs for rollout and training
if [ "${COLOCATE:-1}" = "1" ]; then
    COLOCATE_FLAG="--colocate"
else
    COLOCATE_FLAG=""
fi
ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-${D_MEM}}"
SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY:-${D_CONC}}"
SERVER_POOL_MAX="${SERVER_POOL_MAX:-${D_POOL}}"
ROUTER_POLICY="${ROUTER_POLICY:-round_robin}"
TP_SIZE="${TP_SIZE:-1}"
SAVE_INTERVAL="${SAVE_INTERVAL:-10}"
EVAL_INTERVAL="${EVAL_INTERVAL:-10}"
SKIP_EVAL_BEFORE_TRAIN="${SKIP_EVAL_BEFORE_TRAIN:-1}"
PREWARM_TEMPLATES="${PREWARM_TEMPLATES:-1}"
DYNAMIC_SAMPLING_FILTER_PATH="${DYNAMIC_SAMPLING_FILTER_PATH-slime.rollout.filter_hub.dynamic_sampling_filters.check_reward_nonzero_std}"

# Optimizer
LR="${LR:-1e-6}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.1}"
ADAM_BETA1="${ADAM_BETA1:-0.9}"
ADAM_BETA2="${ADAM_BETA2:-0.98}"

# GRPO
KL_LOSS_COEF="${KL_LOSS_COEF:-0.001}"
EPS_CLIP="${EPS_CLIP:-0.2}"
EPS_CLIP_HIGH="${EPS_CLIP_HIGH:-0.28}"

# AWM environment
AWM_MAX_TURNS="${AWM_MAX_TURNS:-15}"
AWM_SERVER_STARTUP_TIMEOUT="${AWM_SERVER_STARTUP_TIMEOUT:-30.0}"
AWM_SERVER_STARTUP_MAX_RETRIES="${AWM_SERVER_STARTUP_MAX_RETRIES:-2}"
AWM_TOOL_TIMEOUT="${AWM_TOOL_TIMEOUT:-30.0}"

# W&B
WANDB_ENABLED="${WANDB_ENABLED:-0}"

echo "Config: rollout=${NUM_ROLLOUT}, batch=${ROLLOUT_BATCH_SIZE}×${N_SAMPLES_PER_PROMPT}, max_resp=${ROLLOUT_MAX_RESPONSE_LEN}, mem_frac=${SGLANG_MEM_FRACTION_STATIC}, servers=${SERVER_POOL_MAX}"

# Training data
TRAIN_DATA="${SCRIPT_DIR}/data/train.jsonl"
VAL_DATA="${SCRIPT_DIR}/data/val.jsonl"

# ── Model architecture (Qwen3-4B) ────────────────────────────────────────
MODEL_ARGS=(
   --swiglu
   --num-layers 36
   --hidden-size 2560
   --ffn-hidden-size 9728
   --num-attention-heads 32
   --group-query-attention
   --num-query-groups 8
   --use-rotary-position-embeddings
   --disable-bias-linear
   --normalization "RMSNorm"
   --norm-epsilon 1e-6
   --rotary-base 1000000
   --vocab-size 151936
   --kv-channels 128
   --qk-layernorm
)

# ── Checkpoint args ───────────────────────────────────────────────────────
CKPT_ARGS=(
   --hf-checkpoint "${HF_CKPT}"
   --ref-load "${REF_CKPT}"
   --load "${RESUME_CKPT}"
   --save "${SAVE_DIR}"
   --save-interval "${SAVE_INTERVAL}"
)

# ── Rollout args ──────────────────────────────────────────────────────────
ROLLOUT_ARGS=(
   --prompt-data "${TRAIN_DATA}"
   --input-key text
   --metadata-key metadata
   --apply-chat-template
   --rollout-shuffle
   --num-rollout "${NUM_ROLLOUT}"
   --rollout-batch-size "${ROLLOUT_BATCH_SIZE}"
   --over-sampling-batch-size "${OVER_SAMPLING_BATCH_SIZE}"
   --n-samples-per-prompt "${N_SAMPLES_PER_PROMPT}"
   --rollout-max-response-len "${ROLLOUT_MAX_RESPONSE_LEN}"
   --rollout-temperature "${ROLLOUT_TEMPERATURE}"
   --global-batch-size "${GLOBAL_BATCH_SIZE}"
   --balance-data
)
if [ -n "${DYNAMIC_SAMPLING_FILTER_PATH}" ]; then
   ROLLOUT_ARGS+=(--dynamic-sampling-filter-path "${DYNAMIC_SAMPLING_FILTER_PATH}")
fi

# ── Eval args ─────────────────────────────────────────────────────────────
EVAL_ARGS=()
if [ "${EVAL_INTERVAL}" -gt 0 ]; then
   EVAL_ARGS+=(--eval-interval "${EVAL_INTERVAL}")
fi
if [ "${SKIP_EVAL_BEFORE_TRAIN}" = "1" ]; then
   EVAL_ARGS+=(--skip-eval-before-train)
fi
EVAL_ARGS+=(
   --eval-prompt-data awm-val "${VAL_DATA}"
   --n-samples-per-eval-prompt 1
   --eval-max-response-len 4096
   --eval-top-k 1
)

# ── Performance args ──────────────────────────────────────────────────────
PERF_ARGS=(
   --tensor-model-parallel-size "${TP_SIZE}"
   --pipeline-model-parallel-size 1
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1
   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1
   --use-dynamic-batch-size
   --max-tokens-per-gpu "${MAX_TOKENS_PER_GPU}"
)
if [ "${TP_SIZE}" -gt 1 ]; then
   PERF_ARGS+=(--sequence-parallel)
fi

# ── GRPO args ─────────────────────────────────────────────────────────────
GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef "${KL_LOSS_COEF}"
   --kl-loss-type low_var_kl
   --entropy-coef 0.0
   --eps-clip "${EPS_CLIP}"
   --eps-clip-high "${EPS_CLIP_HIGH}"
)

# ── Optimizer args ────────────────────────────────────────────────────────
OPTIMIZER_ARGS=(
   --optimizer adam
   --lr "${LR}"
   --lr-decay-style constant
   --weight-decay "${WEIGHT_DECAY}"
   --adam-beta1 "${ADAM_BETA1}"
   --adam-beta2 "${ADAM_BETA2}"
)

# ── SGLang args ───────────────────────────────────────────────────────────
SGLANG_ARGS=(
   --rollout-num-gpus-per-engine "${ROLLOUT_NUM_GPUS_PER_ENGINE}"
   --sglang-mem-fraction-static "${SGLANG_MEM_FRACTION_STATIC}"
   --sglang-server-concurrency "${SGLANG_SERVER_CONCURRENCY}"
)

ROUTER_ARGS=(
   --router-policy "${ROUTER_POLICY}"
)

# ── Misc args ─────────────────────────────────────────────────────────────
MISC_ARGS=(
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --no-gradient-accumulation-fusion
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
   --no-save-optim
   --no-save-rng
)

# ── Use /dev/shm (RAM) for MCP databases — fastest for small file I/O ────
# SQLite on NFS is extremely slow for the metadata-heavy access patterns
# used by MCP servers.  /dev/shm is in-memory and ideal for this.
# Typical usage: <200 MB total (16 servers × small DBs).
AWM_LOCAL_DB_DIR="/dev/shm/awm_databases_${USER}"
mkdir -p "${AWM_LOCAL_DB_DIR}"
echo "Using /dev/shm (RAM) for MCP databases: ${AWM_LOCAL_DB_DIR}"

# ── Generate runtime AWM config ──────────────────────────────────────────
AWM_RUNTIME_CONFIG="${SCRIPT_DIR}/.awm_config_runtime.yaml"
cat > "${AWM_RUNTIME_CONFIG}" << YAML_EOF
# Auto-generated by run_awm_grpo.sh — do not edit.
# GPU profile: ${GPU_PROFILE} (${GPU_MEM_GB} GB)
max_turns: ${AWM_MAX_TURNS}
server_startup_timeout: ${AWM_SERVER_STARTUP_TIMEOUT}
server_startup_max_retries: ${AWM_SERVER_STARTUP_MAX_RETRIES}
server_pool_max_servers: ${SERVER_POOL_MAX}
server_pool_acquire_poll_interval: 0.05
tool_timeout: ${AWM_TOOL_TIMEOUT}
awm_max_concurrent_samples: 0
rollout_trace_dir: ${SCRIPT_DIR}/logs/rollouts
live_rollout_trace_dir: ${SCRIPT_DIR}/logs/rollouts_live
awm_root: ${AWM_DIR}
awm_db_schema_path: ${AWM_DIR}/outputs/gen_db.jsonl
awm_sample_path: ${AWM_DIR}/outputs/gen_sample.jsonl
awm_verifier_path: ${AWM_DIR}/outputs/gen_verifier.pure_code.jsonl
awm_envs_path: ${AWM_DIR}/outputs/gen_envs.jsonl
awm_db_dir: ${AWM_LOCAL_DB_DIR}
YAML_EOF

# ── Custom args (AWM rollout + reward) ────────────────────────────────────
CUSTOM_ARGS=(
   --custom-generate-function-path rollout.generate
   --custom-rm-path reward.async_rm
   --custom-rollout-log-function-path rollout_logging.log_rollout_data
   --custom-config-path "${AWM_RUNTIME_CONFIG}"
)

# ── Weights & Biases ─────────────────────────────────────────────────────
WANDB_ARGS=()
if [ "${WANDB_ENABLED}" = "1" ]; then
   WANDB_ARGS+=(--use-wandb)
   [ -n "${WANDB_PROJECT}" ] && WANDB_ARGS+=(--wandb-project "${WANDB_PROJECT}")
   [ -n "${WANDB_GROUP}" ]   && WANDB_ARGS+=(--wandb-group "${WANDB_GROUP}")
   [ -n "${WANDB_KEY}" ]     && WANDB_ARGS+=(--wandb-key "${WANDB_KEY}")
fi

# ── Launch Ray ────────────────────────────────────────────────────────────
export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}

if [ "${PREWARM_TEMPLATES}" = "1" ]; then
   echo "Prewarming template databases..."
   PYTHONPATH="${AWM_DIR}:${SCRIPT_DIR}:${PYTHONPATH:-}" python "${SCRIPT_DIR}/prewarm_templates.py" \
      --prompt-data "${TRAIN_DATA}" "${VAL_DATA}" \
      --db-schema-path "${AWM_DIR}/outputs/gen_db.jsonl" \
      --sample-path "${AWM_DIR}/outputs/gen_sample.jsonl" \
      --verifier-path "${AWM_DIR}/outputs/gen_verifier.pure_code.jsonl" \
      --envs-path "${AWM_DIR}/outputs/gen_envs.jsonl" \
      --db-dir "${AWM_DIR}/outputs/databases"
   echo "Prewarm done."
fi

ray start --head \
    --node-ip-address "${MASTER_ADDR}" \
    --num-gpus ${NUM_GPUS} \
    --disable-usage-stats \
    --dashboard-host=0.0.0.0 \
    --dashboard-port=8265

# Wait for Ray dashboard
echo "Waiting for Ray dashboard..."
for i in $(seq 1 30); do
    if curl -s http://127.0.0.1:8265/api/version >/dev/null 2>&1; then
        echo "Ray dashboard ready."
        break
    fi
    sleep 1
done

# ── Build runtime env ─────────────────────────────────────────────────────
RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"${MEGATRON_DIR}:${SCRIPT_DIR}:${SLIME_DIR}:${AWM_DIR}\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\",
    \"NCCL_NVLS_ENABLE\": \"${HAS_NVLINK}\",
    \"MASTER_ADDR\": \"${MASTER_ADDR}\",
    \"no_proxy\": \"127.0.0.1,${MASTER_ADDR}\",
    \"OPENBLAS_NUM_THREADS\": \"${OPENBLAS_NUM_THREADS}\",
    \"OMP_NUM_THREADS\": \"${OMP_NUM_THREADS}\",
    \"MKL_NUM_THREADS\": \"${MKL_NUM_THREADS}\",
    \"NUMEXPR_NUM_THREADS\": \"${NUMEXPR_NUM_THREADS}\",
    \"RAYON_NUM_THREADS\": \"${RAYON_NUM_THREADS}\",
    \"TOKENIZERS_PARALLELISM\": \"${TOKENIZERS_PARALLELISM}\"
  }
}"

# ── Submit training job ───────────────────────────────────────────────────
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 "${SLIME_DIR}/train.py" \
   --actor-num-nodes 1 \
   --actor-num-gpus-per-node ${NUM_GPUS} \
   --rollout-num-gpus ${ROLLOUT_NUM_GPUS} \
   --num-gpus-per-node ${NUM_GPUS} \
   --colocate \
   "${MODEL_ARGS[@]}" \
   "${CKPT_ARGS[@]}" \
   "${ROLLOUT_ARGS[@]}" \
   "${OPTIMIZER_ARGS[@]}" \
   "${GRPO_ARGS[@]}" \
   "${PERF_ARGS[@]}" \
   "${EVAL_ARGS[@]}" \
   "${SGLANG_ARGS[@]}" \
   "${ROUTER_ARGS[@]}" \
   "${MISC_ARGS[@]}" \
   "${CUSTOM_ARGS[@]}" \
   "${WANDB_ARGS[@]}"
